// <auto-generated />
using System;
using FlashMemo.Model.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashMemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221153055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CardEntityTag", b =>
                {
                    b.Property<long>("CardsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("CardEntityTag");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<long>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Due")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuried")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LearningStage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Answer")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("AnswerTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewCardState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("CardLogs", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.Deck", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OptionsId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentDeckId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OptionsId");

                    b.HasIndex("ParentDeckId");

                    b.HasIndex("UserId");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.DeckOptionsEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DeckOptions", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.LastSessionData", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoadedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastUsedDeckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LastSessionData");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.Tag", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntColor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CardEntityTag", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashMemo.Model.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardLog", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.CardEntity", "Card")
                        .WithMany("CardLogs")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId");

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.Deck", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.DeckOptionsEntity", "Options")
                        .WithMany("Decks")
                        .HasForeignKey("OptionsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlashMemo.Model.Persistence.Deck", "ParentDeck")
                        .WithMany("ChildrenDecks")
                        .HasForeignKey("ParentDeckId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Options");

                    b.Navigation("ParentDeck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.DeckOptionsEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("DeckOptions")
                        .HasForeignKey("UserId");

                    b.OwnsOne("FlashMemo.Model.Persistence.DeckOptionsEntity+DailyLimitsOpt", "DailyLimits", b1 =>
                        {
                            b1.Property<long>("DeckOptionsEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DailyLessonsLimit")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DailyReviewsLimit")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DeckOptionsEntityId");

                            b1.ToTable("DeckOptions");

                            b1.WithOwner()
                                .HasForeignKey("DeckOptionsEntityId");
                        });

                    b.OwnsOne("FlashMemo.Model.Persistence.DeckOptionsEntity+SchedulingOpt", "Scheduling", b1 =>
                        {
                            b1.Property<long>("DeckOptionsEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AgainOnReviewStage")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("EasyMultiplier")
                                .HasColumnType("REAL");

                            b1.Property<int>("EasyOnNewDayCount")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("GoodMultiplier")
                                .HasColumnType("REAL");

                            b1.Property<int>("GoodOnNewStage")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("GraduateDayCount")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("HardMultiplier")
                                .HasColumnType("REAL");

                            b1.Property<int>("HardOnNewStage")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("LearningStages")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("DeckOptionsEntityId");

                            b1.ToTable("DeckOptions");

                            b1.WithOwner()
                                .HasForeignKey("DeckOptionsEntityId");
                        });

                    b.OwnsOne("FlashMemo.Model.Persistence.DeckOptionsEntity+SortingOpt", "Sorting", b1 =>
                        {
                            b1.Property<long>("DeckOptionsEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CardStateOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("LessonsOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("LessonsSortDir")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ReviewsOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ReviewsSortDir")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DeckOptionsEntityId");

                            b1.ToTable("DeckOptions");

                            b1.WithOwner()
                                .HasForeignKey("DeckOptionsEntityId");
                        });

                    b.Navigation("DailyLimits")
                        .IsRequired();

                    b.Navigation("Scheduling")
                        .IsRequired();

                    b.Navigation("Sorting")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.Tag", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.UserEntity", b =>
                {
                    b.OwnsOne("FlashMemo.Model.Persistence.UserOptions", "Options", b1 =>
                        {
                            b1.Property<long>("UserEntityId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.Navigation("Options")
                        .IsRequired();
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardEntity", b =>
                {
                    b.Navigation("CardLogs");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.Deck", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("ChildrenDecks");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.DeckOptionsEntity", b =>
                {
                    b.Navigation("Decks");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.UserEntity", b =>
                {
                    b.Navigation("DeckOptions");

                    b.Navigation("Decks");

                    b.Navigation("Logs");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
