// <auto-generated />
using System;
using FlashMemo.Model.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashMemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108132552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("CardEntityTagEntity", b =>
                {
                    b.Property<long>("CardsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("CardEntityTagEntity");
                });

            modelBuilder.Entity("FlashMemo.Model.DeckOptions", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DeckOptions", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<long>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrontContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuried")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LearningStage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextReview")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Answer")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("AnswerTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewCardState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("CardLogs", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.DeckEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("OptionsId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentDeckId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OptionsId");

                    b.HasIndex("ParentDeckId");

                    b.HasIndex("UserId");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.TagEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CardEntityTagEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashMemo.Model.Persistence.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashMemo.Model.DeckOptions", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("DeckOptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FlashMemo.Model.DeckOptions+DailyLimitsOpt", "DailyLimits", b1 =>
                        {
                            b1.Property<long>("DeckOptionsId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DailyLessonsLimit")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DailyReviewsLimit")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DeckOptionsId");

                            b1.ToTable("DeckOptions");

                            b1.WithOwner()
                                .HasForeignKey("DeckOptionsId");
                        });

                    b.OwnsOne("FlashMemo.Model.DeckOptions+OrderingOpt", "Sorting", b1 =>
                        {
                            b1.Property<long>("DeckOptionsId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CardTypeOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("NewCardSortOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ReviewSortOrder")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DeckOptionsId");

                            b1.ToTable("DeckOptions");

                            b1.WithOwner()
                                .HasForeignKey("DeckOptionsId");
                        });

                    b.OwnsOne("FlashMemo.Model.DeckOptions+SchedulingOpt", "Scheduling", b1 =>
                        {
                            b1.Property<long>("DeckOptionsId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AgainDayCount")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AgainStageFallback")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("EasyMultiplier")
                                .HasColumnType("REAL");

                            b1.Property<int>("EasyOnNewDayCount")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("GoodMultiplier")
                                .HasColumnType("REAL");

                            b1.Property<int>("GoodOnNewStage")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("HardMultiplier")
                                .HasColumnType("REAL");

                            b1.Property<int>("HardOnNewStage")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("LearningStages")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("DeckOptionsId");

                            b1.ToTable("DeckOptions");

                            b1.WithOwner()
                                .HasForeignKey("DeckOptionsId");
                        });

                    b.Navigation("DailyLimits")
                        .IsRequired();

                    b.Navigation("Scheduling")
                        .IsRequired();

                    b.Navigation("Sorting")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.DeckEntity", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardLogEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.CardEntity", "Card")
                        .WithMany("CardLogs")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId");

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.DeckEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.DeckOptions", "Options")
                        .WithMany("DecksUsingThis")
                        .HasForeignKey("OptionsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlashMemo.Model.Persistence.DeckEntity", "ParentDeck")
                        .WithMany("ChildrenDecks")
                        .HasForeignKey("ParentDeckId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId");

                    b.Navigation("Options");

                    b.Navigation("ParentDeck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.TagEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.UserEntity", b =>
                {
                    b.OwnsOne("FlashMemo.Model.UserOptions", "Options", b1 =>
                        {
                            b1.Property<long>("UserEntityId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.Navigation("Options")
                        .IsRequired();
                });

            modelBuilder.Entity("FlashMemo.Model.DeckOptions", b =>
                {
                    b.Navigation("DecksUsingThis");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardEntity", b =>
                {
                    b.Navigation("CardLogs");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.DeckEntity", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("ChildrenDecks");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.UserEntity", b =>
                {
                    b.Navigation("DeckOptions");

                    b.Navigation("Decks");

                    b.Navigation("Logs");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
