// <auto-generated />
using System;
using FlashMemo.Model.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashMemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("CardEntityTagEntity", b =>
                {
                    b.Property<long>("CardsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("CardEntityTagEntity");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrontContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuried")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LearningStage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextReview")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Answer")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("AnswerTime")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewCardState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("CardLogs", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.DeckEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SchedulerId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SchedulerId");

                    b.HasIndex("UserId");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.SchedulerEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgainDayCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgainStageFallback")
                        .HasColumnType("INTEGER");

                    b.Property<float>("EasyMultiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("EasyOnNewDayCount")
                        .HasColumnType("INTEGER");

                    b.Property<float>("GoodMultiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("GoodOnNewStage")
                        .HasColumnType("INTEGER");

                    b.Property<float>("HardMultiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("HardOnNewStage")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("LearningStages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Schedulers", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.TagEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CardEntityTagEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashMemo.Model.Persistence.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.DeckEntity", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.CardLogEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.CardEntity", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");

                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId");

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.DeckEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.SchedulerEntity", "Scheduler")
                        .WithMany("Decks")
                        .HasForeignKey("SchedulerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId");

                    b.Navigation("Scheduler");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.SchedulerEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("SchedulerPresets")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.TagEntity", b =>
                {
                    b.HasOne("FlashMemo.Model.Persistence.UserEntity", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.DeckEntity", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.SchedulerEntity", b =>
                {
                    b.Navigation("Decks");
                });

            modelBuilder.Entity("FlashMemo.Model.Persistence.UserEntity", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("Logs");

                    b.Navigation("SchedulerPresets");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
